name: Tests

on: [ push ]

jobs:
  unit_tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Unit tests
        run: gradle test